name: tokens minting insight

on:
  workflow_dispatch:

jobs:
  # The test prooves, all jobs mint thier own GITHUB_TOKEN. Hence tokens scope is limited to a job.
  read1:
    runs-on: ubuntu-latest

    steps:      
      - name: Run a multi-line script
        run: |          
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          echo "${GHCR_TOKEN}"
  read2:
    runs-on: ubuntu-latest

    steps:      
      - name: Run a multi-line script
        run: |          
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          echo "${GHCR_TOKEN}"
