on:
  issues:
    types: [opened, edited, milestoned, closed]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  job1:  
    runs-on: ubuntu-latest
    steps:
      - name: Checking out!
        uses: actions/checkout@v3
      - name: get all releases
        run: |
          gh release list
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
