name: Read manifest of an OCI image on GHCR

on:
  workflow_dispatch:

jobs:  
  read:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Run a multi-line script
        run: |
          nwo="srahul3/oras_artifact"
          tag="1.0.0"
          host="https://ghcr.io"
          manifest_uri="${host}/v2/${nwo}/manifests/${tag}"
          GHCR_TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          MANIFEST=$(curl -X GET "${manifest_uri}" -H "Authorization: Bearer ${GHCR_TOKEN}")
          echo $(MANIFEST)
          
