name: 'publish-action'
on: # rebuild any PRs and main branch changes
  release:
    types: [created, edited]
  repository_dispatch:
    types: [actions-package-migrate]

jobs:
  package-and-publish: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest    
    steps:
      - name: Set the git_tag env
        env:
          RELEASE_REF: ${{ github.event.payload.release.tag_name}}
          MIGRATION_REF: ${{ github.event.client_payload.release.tag_name}}
        run: |
          if ${RELEASE_REF}; then
            echo 'resolving the `ref` from the release event'
            echo "tag_name=${RELEASE_REF}"
            echo "tag_name=${RELEASE_REF}" >> $GITHUB_ENV
          elif ${MIGRATION_REF}; then
            echo 'resolving the `ref` from the release event'
            echo "tag_name=${MIGRATION_REF}" >> $GITHUB_ENV
          else
            exit 1
          fi
      - name: test        
        run: |
          echo "${{ env.tag_name }}"
      - name: Checking out!
        uses: actions/checkout@v3
        with:
           ref: ${{ env.tag_name }}
       
      - name: Publish action 
        uses: actions-on-packages/package-action@0.4.1
