name: 'publish-action'
on: # rebuild any PRs and main branch changes
  release:
    types: [created, edited]
  repository_dispatch:
    types: [actions-package-migrate]

jobs:
  package-and-publish: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Set git_tag
        id: ref
        run: |
          if ${{ github.event.payload.release.tag_name}} != ''
            ref = ${{ github.event.payload.release.tag_name}}
          else if ${{ github.event.client_payload.release.tag_name}} != ''
            ref = ${{ github.event.client_payload.release.tag_name}}
          else
            exit 1          
          echo "value=$ref" >> $GITHUB_OUTPUT
      
      - name: Checking out!
        uses: actions/checkout@v3
        with:
           ref: ${{ steps.ref.outputs.value }}
     
      - name: Print github context payload
        run: echo '${{ toJSON(github) }}'
        
      - name: Print release event payload
        run: echo '${{ toJSON(github.event.payload.release) }}'
        
      - name: Publish action 
        uses: actions-on-packages/package-action@0.4.1
