on:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  job1:  
    runs-on: ubuntu-latest
    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
