name: Listening repository_dispatch
on:
  repository_dispatch:
    types: [aop-migrate]

jobs:  
  build:    
    runs-on: ubuntu-latest

    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Run a one-line script
        run: echo "${{ github.event.client_payload.release.tag_name }}"
      - name: Run a one-line script 2
        run: echo "${{ github.event.client_payload.release.id }}"
