on:
  workflow_dispatch:
    
jobs:
  job1:    
    runs-on: ubuntu-latest
    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/srahul3/A2ZActions/dispatches'
          method: 'POST'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ github.token }}"}'
          data: '{"event_type":"actions-package-migrate","client_payload":{"release":{"tag_name":"v1.1.1", "id":"12345"}}}'

