name: Listening repository_dispatch
on:
  repository_dispatch:
    types: [aop-migrate]

jobs:  
  build:    
    runs-on: ubuntu-latest

    steps:      
      - name: Run a one-line script
        run: echo "${{ github.event.payload.release.tag_name }}"
      - name: Run a one-line script 2
        run: echo "${{ github.event.payload.release.id }}"
