on:
  workflow_dispatch:
    
jobs:
  job1:    
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \          
          --header 'Authorization: Bearer ${{ github.token }}' \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"aop-migrate","client_payload":{"unit":false,"integration":true, "message": "hello from actions!"}}'
          --fail
