on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  job1:    
    runs-on: ubuntu-latest
    steps:
      - name: Checking out!
        uses: actions/checkout@v2.x      
